import CodeBlock from "@/components/docs/CodeBlock";
import Link from "next/link";

export default function CiCd() {
  return (
    <>
      <h1 style={{ fontFamily: "var(--font-space-grotesk)" }}>CI/CD Integration</h1>
      <p className="docs-lead">
        Diff Guardian integrates with GitHub Actions to automatically analyze
        every pull request and post a structured comment with the results.
      </p>

      <hr className="docs-divider" />

      <h2 id="github-actions">GitHub Actions</h2>
      <p>
        The recommended approach is the workflow generated by{" "}
        <Link href="/docs/cli/init">npx dg init</Link>. It runs on every PR
        targeting main or master.
      </p>
      <CodeBlock
        filename=".github/workflows/diff-guardian.yml"
        language="yaml"
        code={`name: "Diff-Guardian"

on:
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    name: API Contract Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build WASM Grammars
        run: npm run build:grammars

      - name: Build
        run: npm run build

      - name: Run Diff-Guardian
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          GITHUB_HEAD_SHA: \${{ github.event.pull_request.head.sha }}
        run: npx dg`}
      />

      <h2 id="key-details">Key details</h2>

      <h3>fetch-depth: 0</h3>
      <p>
        The <code>fetch-depth: 0</code> option ensures the full git history is
        available. Diff Guardian needs to access both the base branch and the PR
        head to extract source files from both refs.
      </p>

      <h3>Smart default mode</h3>
      <p>
        When <code>npx dg</code> runs without arguments inside GitHub Actions,
        it automatically detects the CI environment and:
      </p>
      <ol>
        <li>Reads <code>GITHUB_BASE_REF</code> as the base ref (e.g., <code>origin/main</code>)</li>
        <li>Reads <code>GITHUB_HEAD_SHA</code> as the head ref (the actual PR commit, not the merge commit)</li>
        <li>Uses the GitHub Reporter to post a PR comment</li>
        <li>Always exits 0 — the PR comment is advisory, not blocking</li>
      </ol>

      <h3>GITHUB_HEAD_SHA</h3>
      <p>
        This is critical. GitHub&apos;s default <code>GITHUB_SHA</code> in PR context
        is a <strong>merge commit</strong> — not the actual head of the PR branch.
        By passing <code>GITHUB_HEAD_SHA</code> explicitly from the event payload,
        Diff Guardian analyzes the correct code.
      </p>

      <h2 id="environment">Environment variables</h2>
      <div className="docs-table-wrapper">
        <table className="docs-table">
          <thead>
            <tr><th>Variable</th><th>Source</th><th>Purpose</th></tr>
          </thead>
          <tbody>
            <tr><td><code>GITHUB_ACTIONS</code></td><td>Auto-set by GitHub</td><td>Triggers CI mode detection in smart default</td></tr>
            <tr><td><code>GITHUB_TOKEN</code></td><td>Secrets</td><td>Used to post PR comments via GitHub API</td></tr>
            <tr><td><code>GITHUB_HEAD_SHA</code></td><td>Workflow env</td><td>The actual PR head commit SHA</td></tr>
            <tr><td><code>GITHUB_BASE_REF</code></td><td>Auto-set by GitHub</td><td>Base branch name (e.g., &quot;main&quot;)</td></tr>
            <tr><td><code>GITHUB_REPOSITORY</code></td><td>Auto-set by GitHub</td><td>Repo slug (e.g., &quot;owner/repo&quot;) for API calls</td></tr>
            <tr><td><code>GITHUB_REF</code></td><td>Auto-set by GitHub</td><td>Used to extract the PR number</td></tr>
          </tbody>
        </table>
      </div>

      <h2 id="exit-codes">Exit codes in CI</h2>
      <div className="docs-table-wrapper">
        <table className="docs-table">
          <thead>
            <tr><th>Code</th><th>Behavior</th></tr>
          </thead>
          <tbody>
            <tr><td><code>0</code></td><td>Always. CI mode is advisory — results are posted as a PR comment, never blocking.</td></tr>
            <tr><td><code>2</code></td><td>Infrastructure failure (missing grammars, OOM). The CI check turns red to alert the team.</td></tr>
          </tbody>
        </table>
      </div>

      <h2 id="pr-comment">PR comment format</h2>
      <p>
        The GitHub Reporter posts a single comment per PR, updating it on each push.
        The comment includes:
      </p>
      <ul>
        <li>A summary table: total changes, breaking count, warning count, safe count</li>
        <li>Detailed per-change breakdown with file paths, line numbers, and rule IDs</li>
        <li>Call-site tracing results for breaking changes</li>
      </ul>

      <h2 id="wasm-caching">WASM grammar caching</h2>
      <p>
        The <code>cache: &apos;npm&apos;</code> setting in the Node.js setup step caches
        <code>node_modules</code> across runs. Since WASM grammars are installed
        as npm packages, they are cached automatically — subsequent CI runs
        skip the grammar download.
      </p>

      <h2 id="related">Related</h2>
      <ul>
        <li><Link href="/docs/cli/init">dg init</Link> — scaffold this workflow</li>
        <li><Link href="/docs/git-hooks">Git Hooks</Link> — local enforcement</li>
        <li><Link href="/docs/cli/compare">dg compare</Link> — manual ref comparison</li>
      </ul>
    </>
  );
}
